# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    exclude:
      - '*'
  tags:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest


steps:
- script: echo $(URBAN_DICTIONARY_KEY)
  env:
    URBAN_DICTIONARY_KEY: $(URBAN_DICTIONARY_KEY)

- script: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y
    echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
  displayName: Install rust
- script: cargo build --all
  displayName: Cargo build
- script: cargo test --all
  displayName: Cargo test

- task: Docker@2
  condition: succeeded()
  inputs:
    containerRegistry: 'Docker hub wordbot'
    repository: 'z0r3f/wordbot-docker'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    arguments: '--build-arg URBAN_DICTIONARY_KEY=$(URBAN_DICTIONARY_KEY)'
    tags: |
      $(Build.SourceBranchName)
      latest
